const COLLECTION_LIST = 'COLLECTION_LIST';
const COLLECTION_CREATE = 'COLLECTION_CREATE';
const COLLECTION_DELETE = "COLLECTION_DELETE";
const COLLECTION_EDIT = "COLLECTION_EDIT"



const types = {
    COLLECTION_LIST,
    COLLECTION_CREATE,
    COLLECTION_DELETE,
    COLLECTION_EDIT
};

export default types;