const COLLECTION_LIST = 'COLLECTION_LIST';
const COLLECTION_CREATE = 'COLLECTION_CREATE';
const COLLECTION_DELETE = "COLLECTION_DELETE"



const types = {
    COLLECTION_LIST,
    COLLECTION_CREATE,
    COLLECTION_DELETE
};

export default types;